// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf6G6EQkRh_3QCeGpxV4P6_Dv2rG4hUhw',
    appId: '1:721173429994:android:72c598057815af6a7fa193',
    messagingSenderId: '721173429994',
    projectId: 'emrapps-prerelease',
    storageBucket: 'emrapps-prerelease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZgoqKJKJUy-ehxwcUQJOEoJ3NxsEcTMY',
    appId: '1:721173429994:ios:0c2328cd1e65225b7fa193',
    messagingSenderId: '721173429994',
    projectId: 'emrapps-prerelease',
    storageBucket: 'emrapps-prerelease.firebasestorage.app',
    iosClientId: '', // This is no longer in GoogleService-Info.plist
    iosBundleId: 'com.emrgroup.emrone.nativeshell.prerelease',
  );
}
