// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs5gGfExmAd3P_JrVXHnGVQz-KGlPWXR8',
    appId: '1:900205646429:android:b1b27bc14c5dfd8edbf3b4',
    messagingSenderId: '900205646429',
    projectId: 'emrappsbeta',
    storageBucket: 'emrappsbeta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnEX8YKj-4eDdKh7U8oTxYlXOLcQtGjSw',
    appId: '1:900205646429:ios:e08a4f893c5ee975dbf3b4',
    messagingSenderId: '900205646429',
    projectId: 'emrappsbeta',
    storageBucket: 'emrappsbeta.appspot.com',
    iosClientId:
        '900205646429-j1dvr7oc7m7fv2na9e4cbrbkfqs3bgmu.apps.googleusercontent.com',
    iosBundleId: 'com.emrgroup.emrone.nativeshell.beta',
  );
}
