// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpr7w0HKJHh6GWKYm_7dO5FMLcGJjXyIk',
    appId: '1:914245545457:android:8f46d90c3f9cc2d40da850',
    messagingSenderId: '914245545457',
    projectId: 'emrappsdev',
    storageBucket: 'emrappsdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgmzw1IAy5rrouoStV9-pMRgpzjIm8wc',
    appId: '1:914245545457:ios:b2e646581c8f1d900da850',
    messagingSenderId: '914245545457',
    projectId: 'emrappsdev',
    storageBucket: 'emrappsdev.appspot.com',
    iosClientId:
        '914245545457-v5uoe2hu4r42m91b1ea7o1bfn1tslj44.apps.googleusercontent.com',
    iosBundleId: 'com.emrgroup.emrone.nativeshell.dev',
  );
}
