// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCigp5qSinHECANRP5EwEvN0qvPWSCd1tg',
    appId: '1:542960845784:android:e64ad33f12c51abbf4a8ad',
    messagingSenderId: '542960845784',
    projectId: 'emrapps',
    storageBucket: 'emrapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRBFjKjgmmVtGpPsvTSmo42udOAfeMko0',
    appId: '1:542960845784:ios:d96d226698d71401f4a8ad',
    messagingSenderId: '542960845784',
    projectId: 'emrapps',
    storageBucket: 'emrapps.appspot.com',
    iosClientId:
        '542960845784-dunau15nc4dr9sn4nh6ihr0fnq93pali.apps.googleusercontent.com',
    iosBundleId: 'com.emrgroup.emrone.nativeshell',
  );
}
