import 'package:emr_one_data_management/screens/query_layout_example/models/fruit.dart';

final List<Fruit> kSampleFruits = [
  Fruit(
    type: FruitType.apple,
    name: 'Apple',
    color: 'Red/Green',
    calories: 52,
    sugarContent: 10.4,
  ),
  Fruit(
    type: FruitType.apricot,
    name: 'Apricot',
    color: 'Orange',
    calories: 48,
    sugarContent: 9.2,
  ),
  Fruit(
    type: FruitType.avocado,
    name: 'Avocado',
    color: 'Green',
    calories: 160,
    sugarContent: 0.7,
  ),
  Fruit(
    type: FruitType.banana,
    name: 'Banana',
    color: 'Yellow',
    calories: 89,
    sugarContent: 12.2,
  ),
  Fruit(
    type: FruitType.blackberry,
    name: 'Blackberry',
    color: 'Dark Purple',
    calories: 43,
    sugarContent: 4.9,
  ),
  Fruit(
    type: FruitType.blueberry,
    name: 'Blueberry',
    color: 'Blue',
    calories: 57,
    sugarContent: 10,
  ),
  Fruit(
    type: FruitType.boysenberry,
    name: 'Boysenberry',
    color: 'Purple',
    calories: 50,
    sugarContent: 9.6,
  ),
  Fruit(
    type: FruitType.cantaloupe,
    name: 'Cantaloupe',
    color: 'Orange',
    calories: 34,
    sugarContent: 8.1,
  ),
  Fruit(
    type: FruitType.cherry,
    name: 'Cherry',
    color: 'Red',
    calories: 63,
    sugarContent: 12.8,
  ),
  Fruit(
    type: FruitType.clementine,
    name: 'Clementine',
    color: 'Orange',
    calories: 47,
    sugarContent: 9.2,
  ),
  Fruit(
    type: FruitType.coconut,
    name: 'Coconut',
    color: 'Brown/White',
    calories: 354,
    sugarContent: 6.2,
  ),
  Fruit(
    type: FruitType.cranberry,
    name: 'Cranberry',
    color: 'Red',
    calories: 46,
    sugarContent: 4,
  ),
  Fruit(
    type: FruitType.date,
    name: 'Date',
    color: 'Brown',
    calories: 282,
    sugarContent: 63.4,
  ),
  Fruit(
    type: FruitType.dragonFruit,
    name: 'Dragon Fruit',
    color: 'Pink/White',
    calories: 50,
    sugarContent: 8,
  ),
  Fruit(
    type: FruitType.durian,
    name: 'Durian',
    color: 'Green/Yellow',
    calories: 150,
    sugarContent: 13,
  ),
  Fruit(
    type: FruitType.elderberry,
    name: 'Elderberry',
    color: 'Dark Purple',
    calories: 73,
    sugarContent: 11.4,
  ),
  Fruit(
    type: FruitType.fig,
    name: 'Fig',
    color: 'Purple/Green',
    calories: 74,
    sugarContent: 16.3,
  ),
  Fruit(
    type: FruitType.gooseberry,
    name: 'Gooseberry',
    color: 'Green',
    calories: 44,
    sugarContent: 8.1,
  ),
  Fruit(
    type: FruitType.grape,
    name: 'Grape',
    color: 'Purple/Green',
    calories: 69,
    sugarContent: 15.5,
  ),
  Fruit(
    type: FruitType.grapefruit,
    name: 'Grapefruit',
    color: 'Pink/Yellow',
    calories: 42,
    sugarContent: 7,
  ),
  Fruit(
    type: FruitType.guava,
    name: 'Guava',
    color: 'Green/Pink',
    calories: 68,
    sugarContent: 9,
  ),
  Fruit(
    type: FruitType.honeydew,
    name: 'Honeydew',
    color: 'Green',
    calories: 36,
    sugarContent: 8.1,
  ),
  Fruit(
    type: FruitType.jackfruit,
    name: 'Jackfruit',
    color: 'Green/Yellow',
    calories: 95,
    sugarContent: 19,
  ),
  Fruit(
    type: FruitType.jujube,
    name: 'Jujube',
    color: 'Red/Brown',
    calories: 79,
    sugarContent: 20.2,
  ),
  Fruit(
    type: FruitType.kiwi,
    name: 'Kiwi',
    color: 'Brown/Green',
    calories: 41,
    sugarContent: 8.9,
  ),
  Fruit(
    type: FruitType.kumquat,
    name: 'Kumquat',
    color: 'Orange',
    calories: 71,
    sugarContent: 9.4,
  ),
  Fruit(
    type: FruitType.lemon,
    name: 'Lemon',
    color: 'Yellow',
    calories: 29,
    sugarContent: 2.5,
  ),
  Fruit(
    type: FruitType.lime,
    name: 'Lime',
    color: 'Green',
    calories: 30,
    sugarContent: 1.7,
  ),
  Fruit(
    type: FruitType.lychee,
    name: 'Lychee',
    color: 'Red/White',
    calories: 66,
    sugarContent: 15.2,
  ),
  Fruit(
    type: FruitType.mandarin,
    name: 'Mandarin',
    color: 'Orange',
    calories: 53,
    sugarContent: 11,
  ),
  Fruit(
    type: FruitType.mango,
    name: 'Mango',
    color: 'Orange/Yellow',
    calories: 60,
    sugarContent: 13.7,
  ),
  Fruit(
    type: FruitType.mangosteen,
    name: 'Mangosteen',
    color: 'Purple/White',
    calories: 73,
    sugarContent: 17.9,
  ),
  Fruit(
    type: FruitType.mulberry,
    name: 'Mulberry',
    color: 'Black/Red',
    calories: 43,
    sugarContent: 8.1,
  ),
  Fruit(
    type: FruitType.nectarine,
    name: 'Nectarine',
    color: 'Orange/Red',
    calories: 44,
    sugarContent: 8.6,
  ),
  Fruit(
    type: FruitType.olive,
    name: 'Olive',
    color: 'Green/Black',
    calories: 115,
    sugarContent: 0.5,
  ),
  Fruit(
    type: FruitType.orange,
    name: 'Orange',
    color: 'Orange',
    calories: 47,
    sugarContent: 9.4,
  ),
  Fruit(
    type: FruitType.papaya,
    name: 'Papaya',
    color: 'Orange',
    calories: 43,
    sugarContent: 7.8,
  ),
  Fruit(
    type: FruitType.passionFruit,
    name: 'Passion Fruit',
    color: 'Purple/Yellow',
    calories: 97,
    sugarContent: 11.2,
  ),
  Fruit(
    type: FruitType.peach,
    name: 'Peach',
    color: 'Orange/Red',
    calories: 39,
    sugarContent: 8.4,
  ),
  Fruit(
    type: FruitType.pear,
    name: 'Pear',
    color: 'Green/Yellow',
    calories: 57,
    sugarContent: 9.8,
  ),
  Fruit(
    type: FruitType.persimmon,
    name: 'Persimmon',
    color: 'Orange',
    calories: 81,
    sugarContent: 18,
  ),
  Fruit(
    type: FruitType.pineapple,
    name: 'Pineapple',
    color: 'Brown/Yellow',
    calories: 50,
    sugarContent: 9.9,
  ),
  Fruit(
    type: FruitType.plantain,
    name: 'Plantain',
    color: 'Green/Yellow',
    calories: 122,
    sugarContent: 14.9,
  ),
  Fruit(
    type: FruitType.plum,
    name: 'Plum',
    color: 'Purple/Red',
    calories: 46,
    sugarContent: 9.9,
  ),
  Fruit(
    type: FruitType.pomegranate,
    name: 'Pomegranate',
    color: 'Red',
    calories: 83,
    sugarContent: 13.7,
  ),
  Fruit(
    type: FruitType.pomelo,
    name: 'Pomelo',
    color: 'Green/Yellow',
    calories: 38,
    sugarContent: 7,
  ),
  Fruit(
    type: FruitType.quince,
    name: 'Quince',
    color: 'Yellow',
    calories: 57,
    sugarContent: 13,
  ),
  Fruit(
    type: FruitType.raspberry,
    name: 'Raspberry',
    color: 'Red',
    calories: 52,
    sugarContent: 4.4,
  ),
  Fruit(
    type: FruitType.redcurrant,
    name: 'Redcurrant',
    color: 'Red',
    calories: 56,
    sugarContent: 7.4,
  ),
  Fruit(
    type: FruitType.starfruit,
    name: 'Starfruit',
    color: 'Yellow/Green',
    calories: 31,
    sugarContent: 3.9,
  ),
  Fruit(
    type: FruitType.strawberry,
    name: 'Strawberry',
    color: 'Red',
    calories: 33,
    sugarContent: 4.9,
  ),
  Fruit(
    type: FruitType.tamarillo,
    name: 'Tamarillo',
    color: 'Red/Yellow',
    calories: 40,
    sugarContent: 8.6,
  ),
  Fruit(
    type: FruitType.tamarind,
    name: 'Tamarind',
    color: 'Brown',
    calories: 239,
    sugarContent: 57,
  ),
  Fruit(
    type: FruitType.tangerine,
    name: 'Tangerine',
    color: 'Orange',
    calories: 53,
    sugarContent: 10.6,
  ),
  Fruit(
    type: FruitType.ugliFruit,
    name: 'Ugli Fruit',
    color: 'Green/Orange',
    calories: 47,
    sugarContent: 8.5,
  ),
  Fruit(
    type: FruitType.watermelon,
    name: 'Watermelon',
    color: 'Green/Red',
    calories: 30,
    sugarContent: 6.2,
  ),
  Fruit(
    type: FruitType.yuzu,
    name: 'Yuzu',
    color: 'Yellow/Green',
    calories: 20,
    sugarContent: 2.5,
  ),
];
