targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/graphql/cam_raven/**
            - lib/graphql/cam_sql/**
          scalars:
            Decimal:
              type: double
            Long:
              type: int
            DateTime:
              type: DateTime
            Date:
              type: DateTime
            Byte:
             type: int
            UUID:
              type: String           
