import 'dart:io';

Future main(args) async {
  switch (args[0]) {
    case 'coverage:clean':
      _coverageClean();
      break;
    case 'coverage:combine':
      await _coverageCombine();
      break;
    case 'coverage:generate-helpers':
      await _coverageGenerateHelpers();
      break;
    case 'coverage:report':
      await _coverageReport();
      break;
    case 'gen-l10n:copy-l10n-files':
      await _copyL10nFiles();
      break;
  }
}

// This specifies the path separator for different platforms.
String _slash({bool escapeBackslash = false}) => Platform.isWindows
    ? escapeBackslash
        ? '\\\\'
        : '\\'
    : '/';

/// Combine parts of a path using the appropriate slash for the platform.
String _combinePaths(List<String> paths) => paths.join(_slash());

/// Open a file using the default application
Future _launch(String filename) async {
  if (Platform.isWindows) {
    await Process.run('cmd', ['/c', 'start', filename]);
  } else {
    await Process.run('/usr/bin/open', [filename]);
  }
}

void _coverageClean() {
  final path =
      _combinePaths([Platform.environment['MELOS_ROOT_PATH']!, 'coverage']);
  final directory = Directory(path);

  if (directory.existsSync()) {
    directory.deleteSync(recursive: true);
  }
}

Future<void> _coverageCombine() async {
  final coverde = Platform.isWindows ? 'coverde.bat' : 'coverde';
  final inputFile = _combinePaths(['coverage', 'lcov.info']);
  final outputFile = _combinePaths(['..', '..', 'coverage', 'lcov.info']);

  // Merge the lcov.info file into the combined one for all packages.
  await Process.run(coverde, [
    'filter',
    '--input',
    inputFile,
    '--output',
    outputFile,
    '--filters',
    '\.g\.dart,\.graphql\.dart,generated_plugin_registrant\.dart,firebase_options.?.?.?.?.?\.dart'
  ]);

  // Work around this bug https://github.com/mrverdant13/coverde/issues/50
  final outputText = await File(outputFile).readAsString();
  final outputTextFixed = outputText.replaceAll(
      RegExp(r'SF:.+' +
          _slash(escapeBackslash: true) +
          'packages' +
          _slash(escapeBackslash: true)),
      'SF:packages' + _slash());
  await File(outputFile).writeAsString(outputTextFixed);
}

Future _coverageGenerateHelpers() async {
  final packagePath = Platform.environment['MELOS_PACKAGE_PATH']!;
  final libPath = _combinePaths([packagePath, 'lib']);
  final packageName = Platform.environment['MELOS_PACKAGE_NAME']!;
  final outputFile = _combinePaths(['test', 'coverage_helper_test.dart']);
  var outputText = '''// DO NOT EDIT THIS FILE MANUALLY
// Run 'melos test:generate-coverage-helper' instead
// (or 'melos test' which calls that too)
// Helper file to make coverage work for all non-generated dart files.
// ignore_for_file: unused_import, directives_ordering

''';

  final entities = await Directory(libPath).list(recursive: true).toList();
  for (var entity in entities) {
    if (entity is File) {
      final path = entity.path.toLowerCase();

      if (!path.endsWith('.dart')) {
        continue;
      }

      if (path.endsWith('.g.dart')) {
        continue;
      }

      if (path.endsWith('.graphql.dart')) {
        continue;
      }

      if (path.endsWith('generated_plugin_registrant.dart')) {
        continue;
      }

      if (path.contains(RegExp(r'main.{0,}?\.dart'))) {
        continue;
      }

      // Skip fullscreen_web.dart because it imports dart:html which isn't
      // available outside of a browser, and causes a breaking test.
      if (path.endsWith('/helpers/fullscreen_web.dart')) {
        continue;
      }

      // Read the file so we can check if it's a "part" file, which we can ignore
      // as it's not a standalone file.
      final fileText = File(entity.path).readAsStringSync();
      if (fileText.startsWith('part of')) {
        continue;
      }

      final importFilename = entity.path
          .replaceFirst(
              RegExp(r'.+' +
                  _slash(escapeBackslash: true) +
                  'lib' +
                  _slash(escapeBackslash: true)),
              '$packageName/')
          .replaceAll('\\', '/');
      outputText += "import 'package:$importFilename';\n";
    }
  }

  outputText += '\n';
  outputText += 'void main() {}\n';
  await File(outputFile).writeAsString(outputText);
}

Future _coverageReport() async {
  final root = Platform.environment['MELOS_ROOT_PATH']!;
  final inputFile = _combinePaths([root, 'coverage', 'lcov.info']);
  final outputFile = _combinePaths([root, 'coverage', 'html']);
  final coverde = Platform.isWindows ? 'coverde.bat' : 'coverde';

  // Generate the HTML report.
  await Process.run(
      coverde, ['report', '--input', inputFile, '--output', outputFile],
      workingDirectory: root);

  // Open the report file.
  final filename = _combinePaths([root, 'coverage', 'html', 'index.html']);
  _launch(filename);
}

Future _copyL10nFiles() async {
  final root = Platform.environment['MELOS_ROOT_PATH']!;
  final packagePath = Platform.environment['MELOS_PACKAGE_PATH']!;

  final sourceFiles = _combinePaths(
      [root, 'packages', 'emr_one_localisations', 'l10n', '*.arb']);
  final target = _combinePaths([packagePath, 'lib', 'l10n']);

  if (Platform.isWindows) {
    await Process.run('cmd', ['/c', 'copy', sourceFiles, target, '/Y']);
  } else {
    await Process.run('/bin/sh', ['-c', 'cp $sourceFiles $target']);
  }
}
