// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.emrgroup.emrone.nativeshell.WorkManagerCallback`
class WorkManagerCallback extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<WorkManagerCallback> $type;

  @jni$_.internal
  WorkManagerCallback.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/emrgroup/emrone/nativeshell/WorkManagerCallback');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<WorkManagerCallback?> nullableType =
      $WorkManagerCallback$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<WorkManagerCallback> type =
      $WorkManagerCallback$Type$();
  static final _id_onComplete = _class.instanceMethodId(
    r'onComplete',
    r'(Ljava/lang/String;Ljava/util/Map;)V',
  );

  static final _onComplete = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public abstract void onComplete(java.lang.String id, java.util.Map<java.lang.String, java.lang.Object> data)`
  void onComplete(
    jni$_.JString? id,
    jni$_.JMap<jni$_.JString?, jni$_.JObject?>? data,
  ) {
    final _$id = id?.reference ?? jni$_.jNullReference;
    final _$data = data?.reference ?? jni$_.jNullReference;
    _onComplete(reference.pointer, _id_onComplete as jni$_.JMethodIDPtr,
            _$id.pointer, _$data.pointer)
        .check();
  }

  static final _id_onProgress = _class.instanceMethodId(
    r'onProgress',
    r'(Ljava/lang/String;I)V',
  );

  static final _onProgress = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>, int)>();

  /// from: `public abstract void onProgress(java.lang.String id, int progress)`
  void onProgress(
    jni$_.JString? id,
    int progress,
  ) {
    final _$id = id?.reference ?? jni$_.jNullReference;
    _onProgress(reference.pointer, _id_onProgress as jni$_.JMethodIDPtr,
            _$id.pointer, progress)
        .check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $WorkManagerCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final jni$_.Pointer<
          jni$_.NativeFunction<
              jni$_.JObjectPtr Function(
                  jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)>>
      _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onComplete(Ljava/lang/String;Ljava/util/Map;)V') {
        _$impls[$p]!.onComplete(
          $a![0]?.as(const jni$_.$JString$Type$(), releaseOriginal: true),
          $a![1]?.as(
              const jni$_.$JMap$Type$<jni$_.JString?, jni$_.JObject?>(
                  jni$_.$JString$NullableType$(),
                  jni$_.$JObject$NullableType$()),
              releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onProgress(Ljava/lang/String;I)V') {
        _$impls[$p]!.onProgress(
          $a![0]?.as(const jni$_.$JString$Type$(), releaseOriginal: true),
          $a![1]!
              .as(const jni$_.$JInteger$Type$(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $WorkManagerCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.emrgroup.emrone.nativeshell.WorkManagerCallback',
      $p,
      _$invokePointer,
      [
        if ($impl.onComplete$async)
          r'onComplete(Ljava/lang/String;Ljava/util/Map;)V',
        if ($impl.onProgress$async) r'onProgress(Ljava/lang/String;I)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory WorkManagerCallback.implement(
    $WorkManagerCallback $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return WorkManagerCallback.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $WorkManagerCallback {
  factory $WorkManagerCallback({
    required void Function(
            jni$_.JString? id, jni$_.JMap<jni$_.JString?, jni$_.JObject?>? data)
        onComplete,
    bool onComplete$async,
    required void Function(jni$_.JString? id, int progress) onProgress,
    bool onProgress$async,
  }) = _$WorkManagerCallback;

  void onComplete(
      jni$_.JString? id, jni$_.JMap<jni$_.JString?, jni$_.JObject?>? data);
  bool get onComplete$async => false;
  void onProgress(jni$_.JString? id, int progress);
  bool get onProgress$async => false;
}

final class _$WorkManagerCallback with $WorkManagerCallback {
  _$WorkManagerCallback({
    required void Function(
            jni$_.JString? id, jni$_.JMap<jni$_.JString?, jni$_.JObject?>? data)
        onComplete,
    this.onComplete$async = false,
    required void Function(jni$_.JString? id, int progress) onProgress,
    this.onProgress$async = false,
  })  : _onComplete = onComplete,
        _onProgress = onProgress;

  final void Function(
          jni$_.JString? id, jni$_.JMap<jni$_.JString?, jni$_.JObject?>? data)
      _onComplete;
  final bool onComplete$async;
  final void Function(jni$_.JString? id, int progress) _onProgress;
  final bool onProgress$async;

  void onComplete(
      jni$_.JString? id, jni$_.JMap<jni$_.JString?, jni$_.JObject?>? data) {
    return _onComplete(id, data);
  }

  void onProgress(jni$_.JString? id, int progress) {
    return _onProgress(id, progress);
  }
}

final class $WorkManagerCallback$NullableType$
    extends jni$_.JType<WorkManagerCallback?> {
  @jni$_.internal
  const $WorkManagerCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/emrgroup/emrone/nativeshell/WorkManagerCallback;';

  @jni$_.internal
  @core$_.override
  WorkManagerCallback? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : WorkManagerCallback.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<WorkManagerCallback?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($WorkManagerCallback$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($WorkManagerCallback$NullableType$) &&
        other is $WorkManagerCallback$NullableType$;
  }
}

final class $WorkManagerCallback$Type$
    extends jni$_.JType<WorkManagerCallback> {
  @jni$_.internal
  const $WorkManagerCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/emrgroup/emrone/nativeshell/WorkManagerCallback;';

  @jni$_.internal
  @core$_.override
  WorkManagerCallback fromReference(jni$_.JReference reference) =>
      WorkManagerCallback.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<WorkManagerCallback?> get nullableType =>
      const $WorkManagerCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($WorkManagerCallback$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($WorkManagerCallback$Type$) &&
        other is $WorkManagerCallback$Type$;
  }
}

/// from: `com.emrgroup.emrone.nativeshell.WorkManagerWrapper`
class WorkManagerWrapper extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<WorkManagerWrapper> $type;

  @jni$_.internal
  WorkManagerWrapper.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/emrgroup/emrone/nativeshell/WorkManagerWrapper');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<WorkManagerWrapper?> nullableType =
      $WorkManagerWrapper$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<WorkManagerWrapper> type =
      $WorkManagerWrapper$Type$();
  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory WorkManagerWrapper() {
    return WorkManagerWrapper.fromReference(
        _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr)
            .reference);
  }

  static final _id_setCallback = _class.instanceMethodId(
    r'setCallback',
    r'(Lcom/emrgroup/emrone/nativeshell/WorkManagerCallback;)V',
  );

  static final _setCallback = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void setCallback(com.emrgroup.emrone.nativeshell.WorkManagerCallback callback)`
  void setCallback(
    WorkManagerCallback? callback,
  ) {
    final _$callback = callback?.reference ?? jni$_.jNullReference;
    _setCallback(reference.pointer, _id_setCallback as jni$_.JMethodIDPtr,
            _$callback.pointer)
        .check();
  }

  static final _id_startObserving = _class.instanceMethodId(
    r'startObserving',
    r'()V',
  );

  static final _startObserving = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void startObserving()`
  void startObserving() {
    _startObserving(reference.pointer, _id_startObserving as jni$_.JMethodIDPtr)
        .check();
  }

  static final _id_stopObserving = _class.instanceMethodId(
    r'stopObserving',
    r'()V',
  );

  static final _stopObserving = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void stopObserving()`
  void stopObserving() {
    _stopObserving(reference.pointer, _id_stopObserving as jni$_.JMethodIDPtr)
        .check();
  }

  static final _id_upload = _class.instanceMethodId(
    r'upload',
    r'(Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _upload = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public java.lang.String upload(java.util.Map<java.lang.String, java.lang.String> defaultHeaders, java.lang.String source, java.lang.String destinationUrl)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? upload(
    jni$_.JMap<jni$_.JString?, jni$_.JString?>? defaultHeaders,
    jni$_.JString? source,
    jni$_.JString? destinationUrl,
  ) {
    final _$defaultHeaders = defaultHeaders?.reference ?? jni$_.jNullReference;
    final _$source = source?.reference ?? jni$_.jNullReference;
    final _$destinationUrl = destinationUrl?.reference ?? jni$_.jNullReference;
    return _upload(
            reference.pointer,
            _id_upload as jni$_.JMethodIDPtr,
            _$defaultHeaders.pointer,
            _$source.pointer,
            _$destinationUrl.pointer)
        .object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_clear = _class.instanceMethodId(
    r'clear',
    r'()V',
  );

  static final _clear = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void clear()`
  void clear() {
    _clear(reference.pointer, _id_clear as jni$_.JMethodIDPtr).check();
  }
}

final class $WorkManagerWrapper$NullableType$
    extends jni$_.JType<WorkManagerWrapper?> {
  @jni$_.internal
  const $WorkManagerWrapper$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/emrgroup/emrone/nativeshell/WorkManagerWrapper;';

  @jni$_.internal
  @core$_.override
  WorkManagerWrapper? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : WorkManagerWrapper.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<WorkManagerWrapper?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($WorkManagerWrapper$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($WorkManagerWrapper$NullableType$) &&
        other is $WorkManagerWrapper$NullableType$;
  }
}

final class $WorkManagerWrapper$Type$ extends jni$_.JType<WorkManagerWrapper> {
  @jni$_.internal
  const $WorkManagerWrapper$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/emrgroup/emrone/nativeshell/WorkManagerWrapper;';

  @jni$_.internal
  @core$_.override
  WorkManagerWrapper fromReference(jni$_.JReference reference) =>
      WorkManagerWrapper.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<WorkManagerWrapper?> get nullableType =>
      const $WorkManagerWrapper$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($WorkManagerWrapper$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($WorkManagerWrapper$Type$) &&
        other is $WorkManagerWrapper$Type$;
  }
}
