# targets:
#   $default:
#     builders:
#       emr_one_builders:
#         enabled: true

# builders:
#   emr_one_builders:
#     import: "package:emr_one_builders/register_routes_builder.dart"
#     builder_factories: ["registerRoutesBuilder"]
#     build_extensions: { r'$lib$': ["module_startup.dart"] }
#     auto_apply: root_package
#     build_to: source
