name: emr_one_builders
description: A library of builders for emr_one
version: 2.0.0

environment:
  sdk: ^3.11.0

resolution: workspace

# dependencies:
#   analyzer: ^9.0.0
#   build: ^4.0.1
#   collection: ^1.19.1
#   file: ^7.0.0
#   glob: ^2.1.1
#   path: ^1.9.0
#   yaml: ^3.1.1

# dev_dependencies:
#   build_test: ^3.4.1
#   source_gen: ^4.0.1
#   test: ^1.25.15
#   very_good_analysis: ^6.0.0

flutter:
  generate: false
