name: emr_one_yard_logistics
description: EMR Apps Module yard_logistics
version: 4.1.0
homepage: EMROne
repository: https://dev.azure.com/emrtf01/EMR_Software/_git/emr_one?version=GBdevelop
publish_to: "none"

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  async: ^2.13.0
  cached_network_image: ^3.2.3
  collection: ^1.19.1
  easy_image_viewer: ^1.4.1
  emr_core_api:
    path: ../emr_core_api
  emr_flutter_theme:
    hosted: https://dartpackages.emrgroup.com
    version: ^2.0.0
  emr_one_core:
    path: ../emr_one_core
  emr_one_theme:
    path: ../emr_one_theme
  emr_sharedtypes:
    path: ../emr_sharedtypes
  equatable: ^2.0.5
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^11.0.0
  gql_exec: ^1.0.0
  http: ^1.6.0
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2874.0
  nested: ^1.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  signals: ^6.2.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  patrol: ^3.11.1
  very_good_analysis: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
