// Mocks generated by Mockito 5.4.6 from annotations
// in emr_one_core/test/networking/resilient_web_socket_channel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:emr_one_core/emr_one_core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SimplePolicy].
///
/// See the documentation for Mockito's code generation for more information.
class MockSimplePolicy extends _i1.Mock implements _i2.SimplePolicy {
  MockSimplePolicy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  set userService(_i2.UserService? _userService) => super.noSuchMethod(
        Invocation.setter(
          #userService,
          _userService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.GetNullableFutureString get getToken => (super.noSuchMethod(
        Invocation.getter(#getToken),
        returnValue: () => _i4.Future<String?>.value(),
      ) as _i2.GetNullableFutureString);

  @override
  _i2.GetShouldRetryFutureBool get shouldRetry => (super.noSuchMethod(
        Invocation.getter(#shouldRetry),
        returnValue: (_i2.RetryContext __p0) => _i4.Future<bool>.value(false),
      ) as _i2.GetShouldRetryFutureBool);

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  Duration get retryDelay => (super.noSuchMethod(
        Invocation.getter(#retryDelay),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#retryDelay),
        ),
      ) as Duration);

  @override
  set getToken(_i2.GetNullableFutureString? _getToken) => super.noSuchMethod(
        Invocation.setter(
          #getToken,
          _getToken,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set uri(Uri? _uri) => super.noSuchMethod(
        Invocation.setter(
          #uri,
          _uri,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set shouldRetry(_i2.GetShouldRetryFutureBool? _shouldRetry) =>
      super.noSuchMethod(
        Invocation.setter(
          #shouldRetry,
          _shouldRetry,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set timeout(Duration? _timeout) => super.noSuchMethod(
        Invocation.setter(
          #timeout,
          _timeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectionMessage(String? _connectionMessage) => super.noSuchMethod(
        Invocation.setter(
          #connectionMessage,
          _connectionMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set retryDelay(Duration? _retryDelay) => super.noSuchMethod(
        Invocation.setter(
          #retryDelay,
          _retryDelay,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Uri getUri({Uri? uri}) => (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [],
          {#uri: uri},
        ),
        returnValue: _FakeUri_1(
          this,
          Invocation.method(
            #getUri,
            [],
            {#uri: uri},
          ),
        ),
      ) as Uri);

  @override
  _i4.Future<Map<String, String>> getDefaultHeaders() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultHeaders,
          [],
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  void willRetry(_i2.RetryContext? retryContext) => super.noSuchMethod(
        Invocation.method(
          #willRetry,
          [retryContext],
        ),
        returnValueForMissingStub: null,
      );
}
