// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdySZCAJ5AcBHfv2W3ck1bWLhEFcviV7Y',
    appId: '1:724135467209:web:45893dec0f06b166e5d518',
    messagingSenderId: '724135467209',
    projectId: 'emrportallive',
    authDomain: 'emrportallive.firebaseapp.com',
    storageBucket: 'emrportallive.appspot.com',
    // measurementId: 'G-5JEYCQYF21',
  );
}
