// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo81IvxmS4SyDilMj4PCrhE2_Si9C8rzk',
    appId: '1:946642457048:web:3e43d7ab21a064ba29a2ad',
    messagingSenderId: '946642457048',
    projectId: 'emrportalbeta',
    authDomain: 'emrportalbeta.firebaseapp.com',
    storageBucket: 'emrportalbeta.appspot.com',
    // measurementId: 'G-LD88PMSN3J',
  );
}
