// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  // emrportaldev settings
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArup_lkaBRnmQ9Gn7QRijRZemLzkeOKsg',
    appId: '1:1073241679018:web:9835c4dfcef7fa3b80dcd3',
    messagingSenderId: '1073241679018',
    projectId: 'emrportaldev',
    authDomain: 'emrportaldev.firebaseapp.com',
    storageBucket: 'emrportaldev.appspot.com',
    // measurementId: 'G-BRR15S85C7',
  );
}
