import 'package:emr_account_registration/signup.dart';

class AccountModel extends BaseAccountModel {
  AccountModel({
    required super.localeCountryCode,
    required super.localeLanguageCode,
    super.locatedAtCountryCode,
    super.firstName,
    super.lastName,
    super.canEmail,
    super.canSms,
    super.canPhone,
    super.canPost,
    super.role,
    super.frequency,
    super.yardCode,
    super.phoneNumberCountryCode,
    super.phoneNumberOriginal,
    super.phoneNumber,
    super.emailAddress,
    super.dialingCode,
    super.accountCode,
    super.userId,
    super.proofOfIdUpdated = false,
    super.addressEntered = false,
    super.isAgreedToTermsAndConditions = false,
    super.paymentDetailsUpdated = false,
    super.proofOfAddressUpdated = false,
    super.proofOfIdType,
    super.proofOfAddressType,
    super.proofOfId,
    super.proofOfAddress,
    super.paidIntoAccount = false,
    super.accountHoldername,
    super.sortCode,
    super.bankAccountNumber,
    super.bankName,
    super.enableCel = false,
  });

  static AccountModel? fromSignupModel(
    SignupModel? signupModel,
  ) {
    if (signupModel == null) {
      return null;
    }
    return AccountModel(
      locatedAtCountryCode: signupModel.locatedAtCountryCode,
      firstName: signupModel.firstName,
      lastName: signupModel.lastName,
      phoneNumber: signupModel.phoneNumber,
      emailAddress: signupModel.emailAddress,
      yardCode: signupModel.yardCode,
      role: signupModel.role,
      frequency: signupModel.frequency,
      canEmail: signupModel.canEmail,
      canPost: signupModel.canPost,
      canPhone: signupModel.canPhone,
      canSms: signupModel.canSms,
      proofOfIdUpdated: signupModel.proofOfIdUpdated,
      proofOfAddressUpdated: signupModel.proofOfAddressUpdated,
      paymentDetailsUpdated: signupModel.paymentDetailsUpdated,
      addressEntered: signupModel.addressEntered,
      accountHoldername: signupModel.accountHoldername,
      bankAccountNumber: signupModel.bankAccountNumber,
      bankName: signupModel.bankName,
      sortCode: signupModel.sortCode,
      enableCel: signupModel.enableCel,
      localeCountryCode: signupModel.localeCountryCode,
      localeLanguageCode: signupModel.localeLanguageCode,
      proofOfIdType: signupModel.proofOfIdType,
      proofOfAddressType: signupModel.proofOfAddressType,
      proofOfId: signupModel.proofOfId,
      proofOfAddress: signupModel.proofOfAddress,
      accountCode: signupModel.accountCode,
      dialingCode: signupModel.dialingCode,
      userId: signupModel.userId,
      isAgreedToTermsAndConditions: signupModel.isAgreedToTermsAndConditions,
      paidIntoAccount: signupModel.paidIntoAccount,
      phoneNumberCountryCode: signupModel.phoneNumberCountryCode,
      phoneNumberOriginal: signupModel.phoneNumberOriginal,
    );
  }
}
