import 'dart:convert';

import 'package:cross_file/cross_file.dart';
import 'package:emr_one_core/emr_one_core.dart';
import 'package:gql/ast.dart';
import 'package:gql/language.dart';
import 'package:http/http.dart';
// ignore: unnecessary_import
import 'package:http_parser/http_parser.dart';
import 'package:uuid/uuid.dart';

typedef FromJson<T> = T Function(Map<String, dynamic> json);

extension DocumentNodeExtensions on DocumentNode {
  /// Executes a GraphQL query or mutation and returns typed data.
  ///
  /// [client] will normally be a [ResilientHttpClient].
  ///
  /// [fromJson] should be the fromJson function generated by graphql_codegen.
  ///
  /// [variables] is optional depending on the GraphQL query/mutation but
  /// should use a 'Variables$...' object generated by graphql_codegen.
  ///
  /// [cacheProvider] is an optional implementation of an [EmrCacheProvider]
  /// instance allowing the request to cache its response. Note that when
  /// [files] are set, the cache will be bypassed.
  ///
  /// [cacheTtl] if [cacheProvider] is provided then this optional value can be
  /// used to specify the lifespan of any cached result.
  ///
  /// [cacheKey] is an optional [String] parameter which can be used to
  /// override the auto-generated key.
  ///
  /// [forceLoad] is an optional [bool] parameter (default:false) which can be
  /// guarantee a network call and update the cache with the result.
  ///
  /// [url] is an optional parameter to specify an absolute URL rather than
  /// defaulting to `graphql`.
  ///
  /// [headers] is an optional [Map<String, String>] parameter and can be used
  /// to set specific headers, such as `Authorization`, for a request.
  /// If [headers] is null or not specified it will default to
  /// `{ 'Content-Type': 'application/json' }`, which should likely be included
  /// when passing in custom headers, but isn't enforced. This parameter would
  /// usually only be called when passing in `HttpClient` rather than a
  /// `ResilientHttpClient` to the [client] parameter.
  ///
  /// [files] is an optional [Map<String, XFile>] or [Map<String, [XFile]>] for
  /// use when uploading file(s). When this is set, the request will be a
  /// [MultipartRequest].
  ///
  /// Example using a `ResilientHttpClient`:
  /// ```dart
  /// final result = await queryDocumentTest.execute(
  ///   httpClient,
  ///   Query$Test.fromJson,
  ///   variables: null,
  /// );
  /// ```
  ///
  /// Example using a standard HTTP Client for arbitrary calls:
  /// final httpClient = Client();
  ///
  /// final response = await queryDocumentPartySearch.execute(
  ///   httpClient,
  ///   Query$PartySearch.fromJson,
  ///   variables: null,
  ///   url: Uri.parse('https://example.com/graphql/'),
  ///   headers: {
  ///     'Content-Type': 'application/json',
  ///     'Authorization': 'Bearer ${await FirebaseLogin.getToken()}'
  ///   },
  /// );
  Future<GraphQLResponse<T>> execute<T>(
    Client client,
    FromJson<T> fromJson, {
    dynamic variables,
    EmrCacheProvider? cacheProvider,
    Duration cacheTtl = Duration.zero,
    String? cacheKey,
    bool forceLoad = false,
    Uri? url,
    Map<String, String>? headers,
    Map<String, dynamic>? files,
  }) async {
    final requestId = const Uuid().v4();
    const source = 'DocumentNodeExtensions.execute';
    EmrLogger.verbose(
      'Begin request',
      source: source,
      params: {
        'requestId': requestId,
        'url': url?.toString() ?? '',
      },
    );

    try {
      final node = definitions.firstWhere(
        (element) => element.runtimeType == OperationDefinitionNode,
      ) as OperationDefinitionNode;

      final json = jsonEncode(<String, dynamic>{
        'operationName': node.name?.value ?? '',
        'query': printNode(this),
        'variables': variables,
      });

      EmrLogger.verbose(
        'Create JSON parameters',
        source: source,
        params: {'requestId': requestId, 'json': json},
      );

      String body;

      if (files != null) {
        EmrLogger.verbose(
          'Add files',
          source: source,
          params: {
            'requestId': requestId,
          },
        );
        final request = MultipartRequest(
          'POST',
          url ?? Uri.parse('graphql'),
        );

        if (headers != null) {
          request.headers.addAll(headers);
        }
        request.headers.addAll({'GraphQL-Preflight': '1'});
        request.fields['operations'] = json;

        // Build the Hot Chocolate GraphQL map of files.
        final fileMap = <String, List<String>>{};
        var fileIndex = -1;

        Future<void> addFileToRequest(XFile file, String key) async {
          fileIndex++;

          request.files.add(
            MultipartFile.fromBytes(
              fileIndex.toString(),
              await file.readAsBytes(),
              filename: file.name,
              contentType: MediaType.parse(
                file.mimeType ?? 'application/octet-stream',
              ),
            ),
          );

          fileMap['"$fileIndex"'] = ['"variables.$key"'];
        }

        for (final entry in files.entries) {
          // If a key is specified but there are no file(s), skip it.
          if (entry.value == null) {
            continue;
          }

          if (entry.value is XFile) {
            final value = entry.value as XFile;

            await addFileToRequest(value, entry.key);
          } else if (entry.value is List<XFile>) {
            final values = entry.value as List<XFile>;

            for (final value in values) {
              await addFileToRequest(
                value,
                '${entry.key}.${values.indexOf(value)}',
              );
            }
          } else {
            throw FormatException(
              'Invalid file type. Expected XFile or List<XFile> but got '
              // ignore: avoid_dynamic_calls
              '${entry.value.runtimeType}',
            );
          }
        }

        request.fields['map'] = fileMap.toString();

        EmrLogger.verbose(
          'Send request',
          source: source,
          params: {
            'requestId': requestId,
            'url': request.url.toString(),
          },
        );
        final response = await client.send(request);
        body = await response.stream.bytesToString();

        EmrLogger.verbose(
          'Response received',
          source: source,
          params: {
            'requestId': requestId,
            'statusCode': response.statusCode.toString(),
            'message': response.reasonPhrase ?? '',
            'body': body,
          },
        );
      } else {
        // Try to resolve previous response from cache if provided
        // (and forceLoad was not specified)
        if (forceLoad == false) {
          final cacheHit =
              await cacheProvider?.get(cacheKey ?? json.hashCode.toString());

          if (cacheHit != null) {
            return GraphQLResponseParser.parseResponse<T>(cacheHit, fromJson);
          }
        }

        EmrLogger.verbose(
          'Send request',
          source: source,
          params: {
            'requestId': requestId,
          },
        );
        final response = await client.post(
          url ?? Uri.parse('graphql'),
          headers: headers ??
              {
                'Content-Type': 'application/json',
              },
          body: json,
        );

        EmrLogger.verbose(
          'Response received',
          source: source,
          params: {
            'requestId': requestId,
            'statusCode': response.statusCode.toString(),
            'message': response.reasonPhrase ?? '',
            'body': response.body,
          },
        );
        body = response.body;
      }

      final parsedResponse =
          GraphQLResponseParser.parseResponse<T>(body, fromJson);

      // Only cache the response if it is OK
      if (parsedResponse.hasErrors() == false) {
        // If a cache provider is passed in then store this result with a ttl
        await cacheProvider?.set(
          cacheKey ?? json.hashCode.toString(),
          body,
          cacheTtl,
        );
      } else {
        EmrLogger.warning(
          'Response has errors',
          source: source,
          params: {
            'requestId': requestId,
            'url': url?.toString() ?? '',
            'errors': parsedResponse.errors.toString(),
          },
        );
      }

      EmrLogger.verbose(
        'Returning parsed response & exiting method',
        source: source,
        params: {
          'requestId': requestId,
        },
      );
      return parsedResponse;
    } on Exception catch (ex, trace) {
      EmrLogger.error(
        'Exception',
        error: ex,
        stackTrace: trace,
        source: source,
        params: {
          'requestId': requestId,
        },
      );
      // Keep the existing behaviour - allow exceptions to propagate out of
      // the method, but we can be sure we've logged it.
      rethrow;
    }
  }
}

extension GraphQLResponseExtensions on GraphQLResponse<dynamic> {
  /// Determine whether the response contains errors.
  bool hasErrors() => errors != null && errors!.isNotEmpty;
}
