import 'dart:io';

import 'package:emr_one_forms_engine/core/store/iform_store.dart';
import 'package:emr_one_forms_engine/emr_one_forms_engine.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

// generated by build_runner. Run *flutter pub run build_runner build* to regen / add more mocks.
import 'emr_one_forms_engine_test.mocks.dart';

@GenerateMocks([
  http.Client,
  IDatabaseManager,
  IConnectivity,
  // IGraphQLClient,
  // IGraphQLClientService
])
void main() {
  final client = MockClient();
  final dbManager = MockIDatabaseManager();
  final connectivity = MockIConnectivity();
  // final graphQLClient = MockIGraphQLClient();
  // final graphQLClientService = MockIGraphQLClientService();
  const testEndpoint = 'http://formsapi.placeholder.com';

  TestWidgetsFlutterBinding.ensureInitialized();

  overrideServices(ServiceContainer services) {
    services.replaceSingleton<IDatabaseManager>(dbManager);
    services.replaceSingleton<IConnectivity>(connectivity);
    // services.replaceSingleton<IGraphQLClientService>(graphQLClientService);
    // when(graphQLClientService.getGraphQLClient(any)).thenReturn(graphQLClient);
    when(connectivity.checkConnectivity())
        .thenAnswer((_) async => ConnectivityResult.connected);
  }

  setUp(() async {
    final testFile = File('test/resources/example.template.json');
    final json = await testFile.readAsString();
    FormsEngine.fromConfig(FormConfiguration(
        formsApiUrl: testEndpoint,
        clientFactory: () => client,
        onRegisterServices: (s) => overrideServices(s),
        userName: 'Test_User',
        userUuid: '00000000-0000-0000-0000-000000000000'));

    await FormsEngine().loadTemplateFromJson(json, '');

    // wait for services to be fully up before testing
    await ServiceContainer().initialize();
  });

  test('parses template.json to model', () async {
    final store = ServiceContainer().get<IFormStore>();

    expect(store.title == 'This is an example form', true,
        reason: 'Should have the correct title');
    // expect(store.components.length == 2, true,
    //     reason: 'Should have 2 components');
    // expect(store.getDataProvider('').length == 2, true,
    //     reason: 'Should have 2 dataProviders');
    // expect(template.sections.length == 1, true,
    //     reason: 'Should have 1 section');
  });

  // test('provides api data', () async {
  //   final store = FormsEngine().store!;

  //   final testObject = [
  //     {'id': 'test-object', 'text': 'test-value'},
  //     {'id': 'test-object-2', 'text': 'test-value-2'}
  //   ];

  //   // mock endpoint repsonse call for api provider
  //   when(client.send(any)).thenAnswer((invoker) async {
  //     final request = invoker.positionalArguments[0] as http.Request;

  //     if (request.url.path == '/mock/endpoint') {
  //       final jsonStr = json.encode(testObject);
  //       return http.StreamedResponse(
  //           http.ByteStream.fromBytes(utf8.encode(jsonStr)), 200);
  //     }

  //     return http.StreamedResponse(http.ByteStream.fromBytes([]), 404);
  //   });

  //   final provider =
  //       store.getDataProvider('api-provider') as ApiRequestDataProvider;

  //   final providedValues = await provider.getNextValues(
  //       reference: DataProviderReference(
  //           id: provider.state.id, parameters: {'add-some': 'true'}));

  //   expect(providedValues.length, testObject.length,
  //       reason: 'Should provide all values');

  //   for (int i = 0; i < providedValues.length; ++i) {
  //     expect(providedValues[i].id, testObject[i]['id'],
  //         reason: 'Index $i should have the same id');
  //     expect(providedValues[i].value, testObject[i]['text'],
  //         reason: 'Index $i should have the same value');
  //   }
  // });

  // test('listens for API data changes', () async {
  //   final store = FormsEngine().store!;

  //   final testObject = [
  //     {'id': 'test-object', 'text': 'test-value'},
  //     {'id': 'test-object-2', 'text': 'test-value-2'}
  //   ];

  //   // mock endpoint repsonse call for api provider
  //   when(client.send(any)).thenAnswer((invoker) async {
  //     final request = invoker.positionalArguments[0] as http.Request;

  //     if (request.url.path == '/mock/endpoint') {
  //       if (request.url.queryParameters.isNotEmpty &&
  //           request.url.queryParameters['add-some'] == 'true') {
  //         testObject.add({'id': 'test-object-3', 'text': 'test-value-3'});
  //       }

  //       final jsonStr = json.encode(testObject);
  //       return http.StreamedResponse(
  //           http.ByteStream.fromBytes(utf8.encode(jsonStr)), 200);
  //     }

  //     return http.StreamedResponse(http.ByteStream.fromBytes([]), 404);
  //   });

  //   final provider =
  //       store.getDataProvider('api-provider') as ApiRequestDataProvider;

  //   final completer = Completer();
  //   var firstRun = true;

  //   provider.listenToValues(onChange: (p0) {
  //     if (firstRun) {
  //       expect(p0.length, 2, reason: 'Should have original values');
  //       provider.getNextValue(
  //           reference: DataProviderReference(
  //               id: provider.state.id, parameters: {'add-some': 'true'}));
  //       firstRun = false;
  //     } else {
  //       expect(testObject.length, 3, reason: 'Should have additional value');
  //       completer.complete();
  //     }
  //   });

  //   await completer.future;
  // }, timeout: const Timeout(Duration(seconds: 5)));

  // test('provides data from GraphQL query', () async {
  //   const objectName = 'list';
  //   const idKey = 'id';
  //   const valueKey = 'name';

  //   final Map<String, dynamic> queryResult = {
  //     objectName: [
  //       {idKey: 1, valueKey: 'value1'},
  //       {idKey: 2, valueKey: 'value2'}
  //     ]
  //   };

  //   when(graphQLClient.executeQuery(
  //           query: anyNamed('query'), variables: anyNamed('variables')))
  //       .thenAnswer((_) async => QueryResult(queryResult, null));

  //   final store = FormsEngine().store!;

  //   final provider =
  //       store.getDataProvider('graphql-provider') as FormDataKeyedProviderBloc;

  //   final values = await provider.getNextValues(
  //       reference: DataProviderReference(id: 'graphql-provider'));

  //   assert(values.length == queryResult[objectName].length,
  //       'Should have all query values');

  //   for (var i = 0; i < values.length; ++i) {
  //     assert(values[i].id == queryResult[objectName][i][idKey].toString(),
  //         'ids should match in results');
  //     assert(values[i].value == queryResult[objectName][i][valueKey],
  //         'values should match in results');
  //   }
  // }, testOn: '!browser', timeout: const Timeout(Duration(seconds: 5)));

  // test('should save changes to db', () async {
  //   final store = ServiceContainer().get<IFormStore>();
  //   final firstQuestion = store.formSections
  //           .where((e) => e.components.any((c) => c is YesNoQuestionComponent))
  //           .first
  //           .components
  //           .firstWhere((c) => c is YesNoQuestionComponent)
  //       as YesNoQuestionComponent;

  //   List<InstanceAuditHistory>? history;
  //   FormInstanceRecord? instance;

  //   final changedValueCallback = Completer<String>();
  //   firstQuestion.addListener((data) {
  //     changedValueCallback.complete(data);
  //   }, emitCurrent: false);

  //   when(connectivity.checkConnectivity())
  //       .thenAnswer((_) => Future.value(ConnectivityResult.wifi));

  //   // have to mock db call b/c sqlflite does not support test framework
  //   when(dbManager.insertFormInstance(
  //           instanceId: anyNamed('instanceId'),
  //           json: anyNamed('json'),
  //           history: anyNamed('history'),
  //           isSubmitted: anyNamed('isSubmitted'),
  //           jobInfo: anyNamed('jobInfo'),
  //           scheduledItemId: anyNamed('scheduledItemId')))
  //       .thenAnswer((invocation) async {
  //     history = invocation.namedArguments[const Symbol('history')];
  //     instance = FormInstanceRecord(
  //         id: 1,
  //         isSubmitted: false,
  //         isUploaded: false,
  //         isUploading: true,
  //         isOnServer: false,
  //         scheduledItemId: '',
  //         json: invocation.namedArguments[const Symbol('json')],
  //         uuid: invocation.namedArguments[const Symbol('instanceId')]);

  //     return instance!;
  //   });

  //   when(dbManager.mediaForUploading()).thenAnswer((_) => Future.value([]));
  //   when(dbManager.instanceDataForUploading())
  //       .thenAnswer((_) => Future.value(instance == null
  //           ? []
  //           : [
  //               FormInstanceDataSet(
  //                   instance!,
  //                   history!
  //                       .map((e) => InstanceAuditHistoryRecord(
  //                           uuid: '',
  //                           instanceId: instance!.id,
  //                           componentId: e.componentId,
  //                           action: e.action,
  //                           details: e.value ?? '',
  //                           userName: e.userName,
  //                           createdDate: e.date,
  //                           isUploading: true))
  //                       .toList())
  //             ]));

  //   firstQuestion.changeValue(YesNoQuestionAnswerValues.yes);

  //   assert(await changedValueCallback.future == YesNoQuestionAnswerValues.yes,
  //       'value should update');

  //   await store.waitForSave();

  //   assert(history?.isNotEmpty == true, 'instance should have history');
  // }, testOn: '!browser');
}
