// Mocks generated by Mockito 5.4.4 from annotations
// in emr_one_forms_engine/test/emr_one_forms_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i6;
import 'dart:typed_data' as _i8;

import 'package:emr_one_forms_engine/core/models/database/hive_audit_history.dart'
    as _i4;
import 'package:emr_one_forms_engine/core/models/database/hive_captured_media.dart'
    as _i11;
import 'package:emr_one_forms_engine/core/models/database/hive_form_instance.dart'
    as _i3;
import 'package:emr_one_forms_engine/core/models/database/hive_form_instance_data_set.dart'
    as _i13;
import 'package:emr_one_forms_engine/core/models/dto/dto_models.dart' as _i12;
import 'package:emr_one_forms_engine/core/models/service/service_models.dart'
    as _i10;
import 'package:emr_one_forms_engine/core/services/interfaces/iconnectivity.dart'
    as _i14;
import 'package:emr_one_forms_engine/core/services/interfaces/idatabase_manager.dart'
    as _i9;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHiveFormInstance_2 extends _i1.SmartFake
    implements _i3.HiveFormInstance {
  _FakeHiveFormInstance_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHiveAuditHistory_3 extends _i1.SmartFake
    implements _i4.HiveAuditHistory {
  _FakeHiveAuditHistory_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);

  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i8.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i5.Future<_i8.Uint8List>);

  @override
  _i5.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i5.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IDatabaseManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatabaseManager extends _i1.Mock implements _i9.IDatabaseManager {
  MockIDatabaseManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.HiveFormInstance> insertFormInstance({
    required String? uuid,
    required String? json,
    required bool? isSubmitted,
    required String? scheduledItemId,
    _i10.InstanceJobData? jobInfo,
    bool? isNewInstance = true,
    List<_i10.InstanceAuditHistory>? history,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertFormInstance,
          [],
          {
            #uuid: uuid,
            #json: json,
            #isSubmitted: isSubmitted,
            #scheduledItemId: scheduledItemId,
            #jobInfo: jobInfo,
            #isNewInstance: isNewInstance,
            #history: history,
          },
        ),
        returnValue:
            _i5.Future<_i3.HiveFormInstance>.value(_FakeHiveFormInstance_2(
          this,
          Invocation.method(
            #insertFormInstance,
            [],
            {
              #uuid: uuid,
              #json: json,
              #isSubmitted: isSubmitted,
              #scheduledItemId: scheduledItemId,
              #jobInfo: jobInfo,
              #isNewInstance: isNewInstance,
              #history: history,
            },
          ),
        )),
      ) as _i5.Future<_i3.HiveFormInstance>);

  @override
  _i5.Future<List<_i11.HiveCapturedMedia>> deleteCapturedMedia({
    required String? uniqueInstanceId,
    required String? componentId,
    required List<_i10.CapturedMedia>? media,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCapturedMedia,
          [],
          {
            #uniqueInstanceId: uniqueInstanceId,
            #componentId: componentId,
            #media: media,
          },
        ),
        returnValue: _i5.Future<List<_i11.HiveCapturedMedia>>.value(
            <_i11.HiveCapturedMedia>[]),
      ) as _i5.Future<List<_i11.HiveCapturedMedia>>);

  @override
  _i5.Future<List<_i11.HiveCapturedMedia>> insertCapturedMedia({
    required String? uniqueInstanceId,
    required String? componentId,
    required List<_i10.CapturedMedia>? media,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCapturedMedia,
          [],
          {
            #uniqueInstanceId: uniqueInstanceId,
            #componentId: componentId,
            #media: media,
          },
        ),
        returnValue: _i5.Future<List<_i11.HiveCapturedMedia>>.value(
            <_i11.HiveCapturedMedia>[]),
      ) as _i5.Future<List<_i11.HiveCapturedMedia>>);

  @override
  _i5.Future<List<_i11.HiveCapturedMedia>> insertDownloadMedia({
    required String? uniqueInstanceId,
    required List<_i12.CapturedMediaDTO>? media,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDownloadMedia,
          [],
          {
            #uniqueInstanceId: uniqueInstanceId,
            #media: media,
          },
        ),
        returnValue: _i5.Future<List<_i11.HiveCapturedMedia>>.value(
            <_i11.HiveCapturedMedia>[]),
      ) as _i5.Future<List<_i11.HiveCapturedMedia>>);

  @override
  _i5.Future<_i4.HiveAuditHistory> insertAuditHistory({
    required String? uniqueInstanceId,
    required _i10.InstanceAuditHistory? historyItem,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAuditHistory,
          [],
          {
            #uniqueInstanceId: uniqueInstanceId,
            #historyItem: historyItem,
          },
        ),
        returnValue:
            _i5.Future<_i4.HiveAuditHistory>.value(_FakeHiveAuditHistory_3(
          this,
          Invocation.method(
            #insertAuditHistory,
            [],
            {
              #uniqueInstanceId: uniqueInstanceId,
              #historyItem: historyItem,
            },
          ),
        )),
      ) as _i5.Future<_i4.HiveAuditHistory>);

  @override
  _i5.Future<void> setCapturedMediaPath(
    String? mediaItemUuid, {
    String? localPath,
    String? url,
    bool? isDownloaded,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCapturedMediaPath,
          [mediaItemUuid],
          {
            #localPath: localPath,
            #url: url,
            #isDownloaded: isDownloaded,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setInstanceUploadSuccess(String? instanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInstanceUploadSuccess,
          [instanceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setInstanceUploadFailed(
    String? instanceId,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInstanceUploadFailed,
          [
            instanceId,
            message,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeUploadedHistoryItems(List<String>? historyIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeUploadedHistoryItems,
          [historyIds],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setAuditHistoryUploadFailed(List<String>? historyIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAuditHistoryUploadFailed,
          [historyIds],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearUploadingFlags() => (super.noSuchMethod(
        Invocation.method(
          #clearUploadingFlags,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i13.HiveFormInstanceDataSet>> instanceDataForUploading() =>
      (super.noSuchMethod(
        Invocation.method(
          #instanceDataForUploading,
          [],
        ),
        returnValue: _i5.Future<List<_i13.HiveFormInstanceDataSet>>.value(
            <_i13.HiveFormInstanceDataSet>[]),
      ) as _i5.Future<List<_i13.HiveFormInstanceDataSet>>);

  @override
  _i5.Future<List<_i11.HiveCapturedMedia>> mediaForUploading() =>
      (super.noSuchMethod(
        Invocation.method(
          #mediaForUploading,
          [],
        ),
        returnValue: _i5.Future<List<_i11.HiveCapturedMedia>>.value(
            <_i11.HiveCapturedMedia>[]),
      ) as _i5.Future<List<_i11.HiveCapturedMedia>>);

  @override
  _i5.Future<void> setMediaUploadSuccess(String? instanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMediaUploadSuccess,
          [instanceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMediaUploadFailed(
    String? instanceId,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMediaUploadFailed,
          [
            instanceId,
            message,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.HiveFormInstance?> findInstance(String? uniqueId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findInstance,
          [uniqueId],
        ),
        returnValue: _i5.Future<_i3.HiveFormInstance?>.value(),
      ) as _i5.Future<_i3.HiveFormInstance?>);

  @override
  _i5.Future<List<_i11.HiveCapturedMedia>> findCapturedMediaForInstance(
          String? uniqueId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCapturedMediaForInstance,
          [uniqueId],
        ),
        returnValue: _i5.Future<List<_i11.HiveCapturedMedia>>.value(
            <_i11.HiveCapturedMedia>[]),
      ) as _i5.Future<List<_i11.HiveCapturedMedia>>);

  @override
  _i5.Future<List<_i4.HiveAuditHistory>> findHistory(
          String? uniqueInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findHistory,
          [uniqueInstanceId],
        ),
        returnValue: _i5.Future<List<_i4.HiveAuditHistory>>.value(
            <_i4.HiveAuditHistory>[]),
      ) as _i5.Future<List<_i4.HiveAuditHistory>>);

  @override
  _i5.Future<List<_i3.HiveFormInstance>?> findLocalInstances() =>
      (super.noSuchMethod(
        Invocation.method(
          #findLocalInstances,
          [],
        ),
        returnValue: _i5.Future<List<_i3.HiveFormInstance>?>.value(),
      ) as _i5.Future<List<_i3.HiveFormInstance>?>);

  @override
  _i5.Future<List<_i3.HiveFormInstance>?> findUploadedInstances() =>
      (super.noSuchMethod(
        Invocation.method(
          #findUploadedInstances,
          [],
        ),
        returnValue: _i5.Future<List<_i3.HiveFormInstance>?>.value(),
      ) as _i5.Future<List<_i3.HiveFormInstance>?>);

  @override
  _i5.Future<List<_i3.HiveFormInstance>?> findLocalInstancesForTemplates() =>
      (super.noSuchMethod(
        Invocation.method(
          #findLocalInstancesForTemplates,
          [],
        ),
        returnValue: _i5.Future<List<_i3.HiveFormInstance>?>.value(),
      ) as _i5.Future<List<_i3.HiveFormInstance>?>);

  @override
  _i5.Future<List<_i3.HiveFormInstance>?> findLocalInstancesNotOnServer() =>
      (super.noSuchMethod(
        Invocation.method(
          #findLocalInstancesNotOnServer,
          [],
        ),
        returnValue: _i5.Future<List<_i3.HiveFormInstance>?>.value(),
      ) as _i5.Future<List<_i3.HiveFormInstance>?>);

  @override
  _i5.Future<List<_i3.HiveFormInstance>?> findInstancesByWorkOrderId(
          String? workOrderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findInstancesByWorkOrderId,
          [workOrderId],
        ),
        returnValue: _i5.Future<List<_i3.HiveFormInstance>?>.value(),
      ) as _i5.Future<List<_i3.HiveFormInstance>?>);

  @override
  _i5.Future<void> removeInstance(String? uniqueId) => (super.noSuchMethod(
        Invocation.method(
          #removeInstance,
          [uniqueId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveImageData(
    String? uuid,
    _i8.Uint8List? imageData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveImageData,
          [
            uuid,
            imageData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i8.Uint8List? getImageData(String? uuid) =>
      (super.noSuchMethod(Invocation.method(
        #getImageData,
        [uuid],
      )) as _i8.Uint8List?);

  @override
  _i5.Future<List<_i13.HiveFormInstanceDataSet>> getInstanceDataForUploading(
          String? instanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInstanceDataForUploading,
          [instanceId],
        ),
        returnValue: _i5.Future<List<_i13.HiveFormInstanceDataSet>>.value(
            <_i13.HiveFormInstanceDataSet>[]),
      ) as _i5.Future<List<_i13.HiveFormInstanceDataSet>>);

  @override
  _i5.Future<List<_i11.HiveCapturedMedia>> getMediaForUploading(
          String? instanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaForUploading,
          [instanceId],
        ),
        returnValue: _i5.Future<List<_i11.HiveCapturedMedia>>.value(
            <_i11.HiveCapturedMedia>[]),
      ) as _i5.Future<List<_i11.HiveCapturedMedia>>);

  @override
  _i5.Future<List<_i3.HiveFormInstance>?> getAllInstances() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllInstances,
          [],
        ),
        returnValue: _i5.Future<List<_i3.HiveFormInstance>?>.value(),
      ) as _i5.Future<List<_i3.HiveFormInstance>?>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IConnectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockIConnectivity extends _i1.Mock implements _i14.IConnectivity {
  MockIConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i14.ConnectivityResult> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i5.Future<_i14.ConnectivityResult>.value(
            _i14.ConnectivityResult.none),
      ) as _i5.Future<_i14.ConnectivityResult>);
}
