name: emr_core_api
description: Services for accessing the Core API schema.
version: 3.0.6
homepage: https://dev.azure.com/emrtf01/EMR_Software/_git/emr_one?version=GBdevelop&path=/packages/emr_core_api
repository: https://dev.azure.com/emrtf01/EMR_Software/_git/emr_one?version=GBdevelop
publish_to: "none"

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  decimal: ^3.2.4
  emr_one_core:
    path: ../emr_one_core
  emr_sharedtypes:
    path: ../emr_sharedtypes
  flutter:
    sdk: flutter
  gql_exec: ^1.0.0
  http: ^1.6.0
  http_parser: ^4.1.2
  json_annotation: ^4.9.0
  provider: ^6.1.5

dev_dependencies:
  analyzer: ^9.0.0
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  graphql_codegen: ^3.0.1
  json_serializable: ^6.8.0
  patrol: ^3.11.1
  very_good_analysis: ^6.0.0
