// Mocks generated by Mockito 5.4.6 from annotations
// in emr_one_core/test/config/app_config_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:emr_one_core/appinsights/azure_application_insights.dart'
    as _i4;
import 'package:emr_one_core/emr_one_core.dart' as _i8;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_remote_config/firebase_remote_config.dart' as _i5;
import 'package:firebase_remote_config_platform_interface/firebase_remote_config_platform_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteConfigSettings_2 extends _i1.SmartFake
    implements _i3.RemoteConfigSettings {
  _FakeRemoteConfigSettings_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteConfigValue_3 extends _i1.SmartFake
    implements _i3.RemoteConfigValue {
  _FakeRemoteConfigValue_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_4 extends _i1.SmartFake implements Duration {
  _FakeDuration_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBufferedProcessor_5 extends _i1.SmartFake
    implements _i4.BufferedProcessor {
  _FakeBufferedProcessor_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTelemetryClient_6 extends _i1.SmartFake
    implements _i4.TelemetryClient {
  _FakeTelemetryClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseRemoteConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseRemoteConfig extends _i1.Mock
    implements _i5.FirebaseRemoteConfig {
  MockFirebaseRemoteConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
      ) as _i2.FirebaseApp);

  @override
  DateTime get lastFetchTime => (super.noSuchMethod(
        Invocation.getter(#lastFetchTime),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#lastFetchTime),
        ),
      ) as DateTime);

  @override
  _i3.RemoteConfigFetchStatus get lastFetchStatus => (super.noSuchMethod(
        Invocation.getter(#lastFetchStatus),
        returnValue: _i3.RemoteConfigFetchStatus.noFetchYet,
      ) as _i3.RemoteConfigFetchStatus);

  @override
  _i3.RemoteConfigSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeRemoteConfigSettings_2(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i3.RemoteConfigSettings);

  @override
  _i6.Stream<_i3.RemoteConfigUpdate> get onConfigUpdated => (super.noSuchMethod(
        Invocation.getter(#onConfigUpdated),
        returnValue: _i6.Stream<_i3.RemoteConfigUpdate>.empty(),
      ) as _i6.Stream<_i3.RemoteConfigUpdate>);

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i6.Future<bool> activate() => (super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> ensureInitialized() => (super.noSuchMethod(
        Invocation.method(
          #ensureInitialized,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> fetch() => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> fetchAndActivate() => (super.noSuchMethod(
        Invocation.method(
          #fetchAndActivate,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  Map<String, _i3.RemoteConfigValue> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <String, _i3.RemoteConfigValue>{},
      ) as Map<String, _i3.RemoteConfigValue>);

  @override
  bool getBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  int getInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValue: 0,
      ) as int);

  @override
  double getDouble(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getDouble,
          [key],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  String getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getString,
            [key],
          ),
        ),
      ) as String);

  @override
  _i3.RemoteConfigValue getValue(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getValue,
          [key],
        ),
        returnValue: _FakeRemoteConfigValue_3(
          this,
          Invocation.method(
            #getValue,
            [key],
          ),
        ),
      ) as _i3.RemoteConfigValue);

  @override
  _i6.Future<void> setConfigSettings(
          _i3.RemoteConfigSettings? remoteConfigSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConfigSettings,
          [remoteConfigSettings],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setDefaults(Map<String, dynamic>? defaultParameters) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDefaults,
          [defaultParameters],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setCustomSignals(Map<String, Object?>? customSignals) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomSignals,
          [customSignals],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [AIHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIHelper extends _i1.Mock implements _i8.AIHelper {
  MockAIHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get instrumentationKey => (super.noSuchMethod(
        Invocation.getter(#instrumentationKey),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#instrumentationKey),
        ),
      ) as String);

  @override
  String get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#app),
        ),
      ) as String);

  @override
  String get env => (super.noSuchMethod(
        Invocation.getter(#env),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#env),
        ),
      ) as String);

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_4(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  bool Function() get enabled => (super.noSuchMethod(
        Invocation.getter(#enabled),
        returnValue: () => false,
      ) as bool Function());

  @override
  _i4.BufferedProcessor get processor => (super.noSuchMethod(
        Invocation.getter(#processor),
        returnValue: _FakeBufferedProcessor_5(
          this,
          Invocation.getter(#processor),
        ),
      ) as _i4.BufferedProcessor);

  @override
  _i4.TelemetryClient get telemetryClient => (super.noSuchMethod(
        Invocation.getter(#telemetryClient),
        returnValue: _FakeTelemetryClient_6(
          this,
          Invocation.getter(#telemetryClient),
        ),
      ) as _i4.TelemetryClient);

  @override
  set processor(_i4.BufferedProcessor? _processor) => super.noSuchMethod(
        Invocation.setter(
          #processor,
          _processor,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set telemetryClient(_i4.TelemetryClient? _telemetryClient) =>
      super.noSuchMethod(
        Invocation.setter(
          #telemetryClient,
          _telemetryClient,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> trackEvent(
    String? name, {
    Map<String, String>? params = const {},
    String? type = 'uiAction',
    _i4.Severity? severity = _i4.Severity.information,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackEvent,
          [name],
          {
            #params: params,
            #type: type,
            #severity: severity,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> submitErrorAsTelemetry({
    required bool? isFatal,
    required Object? error,
    required StackTrace? trace,
    Map<String, Object>? additionalProperties = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitErrorAsTelemetry,
          [],
          {
            #isFatal: isFatal,
            #error: error,
            #trace: trace,
            #additionalProperties: additionalProperties,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
