// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1psQMyVshkcY8Z7xya35Bg31Ay7tEsZA',
    appId: '1:1026682224027:web:69f89fa7ffc80fd811b53e',
    messagingSenderId: '1026682224027',
    projectId: 'emrappsapple',
    authDomain: 'emrappsapple.firebaseapp.com',
    storageBucket: 'emrappsapple.firebasestorage.app',
    measurementId: 'G-6709LK5T2N',
  );
}
