// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOz6Fq4jKzelNKJvluiD0H5gs7vYwxsFs',
    appId: '1:900205646429:web:0c82a98cc34cce66dbf3b4',
    messagingSenderId: '900205646429',
    projectId: 'emrappsbeta',
    authDomain: 'emrappsbeta.firebaseapp.com',
    storageBucket: 'emrappsbeta.appspot.com',
    measurementId: 'G-LD88PMSN3J',
  );
}
