// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChR2ghEdmkBwz2hSQT3ugFwAwCQWN73ko',
    appId: '1:943505016268:web:ee08e0a91efc9bdd540969',
    messagingSenderId: '943505016268',
    projectId: 'emrappsappletest',
    authDomain: 'emrappsappletest.firebaseapp.com',
    storageBucket: 'emrappsappletest.firebasestorage.app',
  );
}
