// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWp1x-yJ9jr5YHRBhtVjhI0w_JkcaDXag',
    appId: '1:914245545457:web:f7918ecaa9045a5c0da850',
    messagingSenderId: '914245545457',
    projectId: 'emrappsdev',
    authDomain: 'emrappsdev.firebaseapp.com',
    storageBucket: 'emrappsdev.appspot.com',
    measurementId: 'G-BRR15S85C7',
  );
}
