// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRLySEwU93B3anLORIDvg3t3gNKK4Y-T0',
    appId: '1:658985340273:web:344ca1ad455ba6841e3ad0',
    messagingSenderId: '658985340273',
    projectId: 'emrappsalpha',
    authDomain: 'emrappsalpha.firebaseapp.com',
    storageBucket: 'emrappsalpha.firebasestorage.app',
    measurementId: 'G-CHR1C1EE7P',
  );
}
