// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANClP3-Q7bWaCB6siDbVPfvLnIraUYggE',
    appId: '1:542960845784:web:3cf4f0f6172bb0a5f4a8ad',
    messagingSenderId: '542960845784',
    projectId: 'emrapps',
    authDomain: 'emrapps.firebaseapp.com',
    storageBucket: 'emrapps.appspot.com',
    measurementId: 'G-5JEYCQYF21',
  );
}
