// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9szeiYHRmYdMw0n95VGOrD52mYL4sVFA',
    appId: '1:721173429994:web:a5b44d8dedb95a0d7fa193',
    messagingSenderId: '721173429994',
    projectId: 'emrapps-prerelease',
    authDomain: 'emrapps-prerelease.firebaseapp.com',
    storageBucket: 'emrapps-prerelease.firebasestorage.app',
    measurementId: 'G-EFNNDVECM6',
  );
}
